/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e2e1",
        surface: "#131313",
        "outline-variant": "#3e484f",
        "primary-fixed": "#c4e7ff",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#ffb2b9",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed": "#68fcbf",
        "on-secondary-container": "#ff97a3",
        "on-primary-fixed": "#001e2c",
        "secondary-container": "#891933",
        "on-error": "#690005",
        "inverse-on-surface": "#313030",
        "surface-container": "#201f1f",
        "on-secondary-fixed": "#400010",
        secondary: "#ffb2b9",
        "inverse-primary": "#00668a",
        "on-error-container": "#ffdad6",
        "surface-tint": "#7bd0ff",
        "primary-fixed-dim": "#7bd0ff",
        "surface-container-high": "#2a2a2a",
        outline: "#87929a",
        "secondary-fixed": "#ffdadc",
        "on-surface-variant": "#bdc8d1",
        "on-primary": "#00354a",
        "on-primary-fixed-variant": "#004c69",
        "surface-bright": "#3a3939",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#45dfa4",
        background: "#131313",
        "on-secondary-fixed-variant": "#891933",
        "surface-dim": "#131313",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        primary: "#8ed5ff",
        "on-tertiary-fixed": "#002114",
        "error-container": "#93000a",
        tertiary: "#4ee6aa",
        "on-tertiary-fixed-variant": "#005137",
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "on-secondary": "#67001f",
        error: "#ffb4ab",
        "on-tertiary-container": "#004e35",
        "tertiary-container": "#22c990",
        "on-tertiary": "#003825",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-xl": "2rem",
        "orbit-gap": "5rem",
        "space-2xs": "0.25rem",
        "viewport-inset": "2rem",
        "space-3xl": "4.5rem",
        "space-4xl": "6rem",
        "space-2xl": "3rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-xl-mobile": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "display-lg-mobile": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "display-xl": ["Space Grotesk"],
        "headline-sm": ["Space Grotesk"],
        "label-sm": ["Space Mono"],
        "label-md": ["Space Mono"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "300" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-xl-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.02em", fontWeight: "300" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "300" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "0em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}